baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'EvokeMadness'
theme = 'ananke'


[params]
  # text_color = ""
  # author = ""
  favicon = "images/engineering-club-logo2.png"
  site_logo = "images/logo.svg"
  # description = "The last theme you'll ever need. Maybe."
	# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  # recent_posts_number = 3
